ALERT_ENABLED = true

ALERT_FROM_NAME = "Trading Scanner 4.3"
ALERT_BUY_SIGNAL_NAME = "Starkes Kaufsignal"
ALERT_PORTFOLIO_SELL_SIGNAL_NAME = "Verkaufen"

ALERT_SMTP_HOST = "mail.gmx.net"
ALERT_SMTP_PORT = 587
ALERT_SMTP_USE_TLS = true
ALERT_SMTP_USE_SSL = false

ALERT_SMTP_USERNAME = "deineadresse@gmx.de"
ALERT_SMTP_PASSWORD = "DEIN_PASSWORT"
ALERT_FROM_EMAIL = "deineadresse@gmx.de"

ALERT_RECIPIENTS = "mail1@gmx.de, mail2@gmail.com"